AWSTemplateFormatVersion: "2010-09-09"
# Parameters:
#   GitHubAccessToken:
#     Type: String
#     Default: "{{resolve:ssm-secure:GithubAccessToken:3}}"
#     NoEcho: true
Resources:
  DeploymentArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        # The guide recommends Enabled but I can't see why
        Status: Suspended
  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref DeploymentArtifactBucket
      RoleArn: arn:aws:iam::763455941045:role/CodeBuild_Serverless_Admin
      DisableInboundStageTransitions:
        - Reason: Manual approval needed for production deployment
          StageName: ManualApproval
      Stages:
        - Name: Source
          Actions:
            - Name: Get-sources
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: MyAppSourceCodeArtifact
              Configuration:
                Owner: tudornsa
                Repo: aws-testing
                Branch: master
                #OAuthToken: ${ssm:/aws/reference/secretsmanager/Github~true} serverless.yml way of doing it:using AWS Secrets Manager
                #OAuthToken: ${ssm:GithubAccessToken~true} # serverless.yml way of doing it: having this in a variable didn't work, but having it inline works?!
                #OAuthToken: "{{resolve:ssm-secure:GithubAccessToken:3}}" #cloudFormation syntax
                OAuthToken: "{{resolve:ssm-secure:GitHubAccessToken:1}}"
              RunOrder: 1 # The order of this action inside this stage
        - Name: Development
          Actions:
            - Name: Deploy-to-Development
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              RunOrder: 1
              Configuration:
                ProjectName: TestAndDeployToDev
              InputArtifacts:
                - Name: MyAppSourceCodeArtifact
        - Name: ManualApproval
          Actions:
            - Name: Manual-Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
        - Name: Production
          Actions:
            - Name: Deploy-to-Production
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              RunOrder: 1
              Configuration:
                ProjectName: DeployToProduction
              InputArtifacts:
                - Name: MyAppSourceCodeArtifact
  TestAndDeployToDev:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: TestAndDeployToDev
      ServiceRole: arn:aws:iam::763455941045:role/CodeBuild_Serverless_Admin
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
          - Name: env
            Value: Dev
          - Name: BUILD_ARTIFACT_BUCKET
            Value: !Ref DeploymentArtifactBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: "buildspecs/buildspec-dev.yaml"
      TimeoutInMinutes: 10
  DeployToProduction:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: DeployToProduction
      ServiceRole: arn:aws:iam::763455941045:role/CodeBuild_Serverless_Admin
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
          - Name: env
            Value: Prd
          - Name: BUILD_ARTIFACT_BUCKET
            Value: !Ref DeploymentArtifactBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: "buildspecs/buildspec-prd.yaml"
      TimeoutInMinutes: 10
